Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true

### DB vm  ####
  config.vm.define "db01" do |db01|
    db01.vm.box = "centos/stream9"
    db01.vm.hostname = "db01"
    db01.vm.network "private_network", ip: "192.168.56.20"
    db01.vm.provider "virtualbox" do |vb|
     vb.memory = "600"
   end
    db01.vm.provision "shell", path: "mysql.sh", args: 'web01'
  end

### MinIO vm  ####
  config.vm.define "minio01" do |minio01|
    minio01.vm.box = "centos/stream9"
    minio01.vm.hostname = "minio01"
    minio01.vm.network "private_network", ip: "192.168.56.5"
    minio01.vm.synced_folder "./secrets", "/tmp/secrets", create: true
    minio01.vm.provider "virtualbox" do |vb|
      vb.memory = "600"
   end
    minio01.vm.provision "shell", path: "minio.sh"
  end

### redis vm  ####
  config.vm.define "rds01" do |rds01|
    rds01.vm.box = "centos/stream9"
    rds01.vm.hostname = "rds01"
    rds01.vm.network "private_network", ip: "192.168.56.25"
    rds01.vm.provider "virtualbox" do |vb|
     vb.memory = "600"
   end
    rds01.vm.provision "shell", path: "redis.sh"
  end

### FastAPI vm  ####
  config.vm.define "py01" do |py01|
    py01.vm.box = "ubuntu/jammy64"
    py01.vm.hostname = "py01"
    py01.vm.network "private_network", ip: "192.168.56.15"
    py01.vm.synced_folder "./secrets", "/tmp/secrets", create: true
    py01.vm.provider "virtualbox" do |vb|
     vb.memory = "4096"
     vb.cpus = 4
   end
    py01.vm.provision "shell", path: "fastapi.sh", args: "web01"
  end

  ### Nginx VM ###
  config.vm.define "web01" do |web01|
    web01.vm.box = "ubuntu/jammy64"
    web01.vm.hostname = "web01"
  web01.vm.network "private_network", ip: "192.168.56.10"
  web01.vm.synced_folder "./secrets", "/tmp/secrets", create: true
#  web01.vm.network "public_network"
  web01.vm.provider "virtualbox" do |vb|
     vb.gui = true
     vb.memory = "800"
   end
  web01.vm.provision "shell", path: "nginx.sh", args: ['db01', 'rds01', 'py01']
end

end
